import type { Metadata } from "next";
import "./globals.css";
import Session from "../context/Sessions";
import Navbar from "../components/Navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Session>
          <Navbar />
          {children}
          </Session>
      </body>
    </html>
  );
}
